name: 'terragrunt'
description: 'Wrapper to execute terragrunt'

inputs:
  working-directory:
    description: 'Terragrunt working directory'
    required: false
    default: './'
  aws-role-arn:
    description: 'AWS IAM role to execute as'
    required: true
  terragrunt-version:
    description: 'Terragrunt version, if set will override `.terragrunt-version` value'
    required: false
    default: 'false'
  terraform-version:
    description: 'Terraform version, if set will override `.terraform-version` value'
    required: false
    default: 'false'
  use-dotversion:
    description: "If set to `'true'` then the action will check the root of the repo for `.terragrunt-version` and `.terraform-version` for version information."
    required: false
    default: 'true'
  aws-region:
    description: "AWS region"
    required: false
    default: 'us-east-1'
  command:
    description: 'Terragrunt command'
    required: true

runs:
  using: 'composite'
  steps:
    # - id: setup
    #   shell: bash
    #   run: |
    #     if [[ ${{ inputs.command }} == "apply" ]]; then
    #       echo 'tf_cmd="apply -auto-approve"' >> $GITHUB_ENV
    #     else
    #       echo "tf_cmd=${{ inputs.command }}" >> $GITHUB_ENV
    #     fi

    - id: versions
      if: ${{ inputs.use-dotversion == 'true' }}
      shell: bash
      run: |
        echo "terraform_version=$(cat .terraform-version)" >> $GITHUB_ENV
        echo "terragrunt_version=$(cat .terragrunt-version)" >> $GITHUB_ENV

    - id: setup-tg
      uses: peter-murray/terragrunt-github-action@v1.0.0
      with:
        terragrunt_version: ${{ inputs.terragrunt-version != 'false' && inputs.terragrunt-version || env.terragrunt_version }}

    - id: setup-tf
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ inputs.terraform-version != 'false' && inputs.terraform-version || env.terraform_version }}

    - id: aws-creds
      uses: aws-actions/configure-aws-credentials@master
      with:
        role-to-assume: ${{ inputs.aws-role-arn }}
        aws-region: ${{ inputs.aws-region }}

    - id: tg-command
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [[ ${{ inputs.command }} == "apply" ]]; then
          TF_CMD="apply -auto-approve"
        else
          TF_CMD=${{ inputs.command }}
        fi
        CMD="terragrunt ${TF_CMD} --terragrunt-non-interactive"
        eval $CMD
