name: 'ww-matrix'
description: 'Generate build matrix based on git base ref'

inputs:
  base-branch:
    description: Git base branch.
    required: true

  main-branch:
    description: Main branch.
    required: false
    default: develop

  prod-branch:
    description: Production deploy branch.
    required: false
    default: master

  rc-branch-regex:
    description: Regex matching rc branch format.
    required: false
    default: '^rc/.*'

outputs:
  matrix:
    description: JSON string containing build matrix

runs:
  using: 'node16'
  main: 'dist/index.js'
