name: 'ww-deploy-apigateway'
description: 'Create an API gateway deployment'

inputs:
  aws-role-arn:
    description: AWS IAM role to execute as
    required: true
  aws-region:
    description: AWS region
    required: false
    default: eu-west-1
  apigateway-name:
    description: API Gateway name, or semi-colon delimited list of names
    required: true
  apigateway-stage-name:
    description: API gateway stage name
    required: false
    default: live

runs:
  using: 'composite'
  steps:
    - id: aws-creds
      uses: aws-actions/configure-aws-credentials@master
      with:
        role-to-assume: ${{ inputs.aws-role-arn }}
        aws-region: ${{ inputs.aws-region }}

    - id: deploy
      shell: bash
      run: |
        for GW_NAME in $(echo "${{ inputs.apigateway-name}}" | sed 's/;/ /'); do
          APIGW_ID=$(aws --region ${{ inputs.aws-region }} apigateway get-rest-apis --query "items[?name=='$GW_NAME'].id" --output text);
          aws --region ${{ inputs.aws-region }} apigateway create-deployment --rest-api-id "$APIGW_ID" --stage-name ${{ inputs.apigateway-stage-name }};
          sleep 10;
        done
