name: 'ww-deploy-apigateway'
description: 'Create an API gateway deployment'

inputs:
  aws-role-arn:
    description: AWS IAM role to execute as
    required: true
  aws-region:
    description: AWS region
    required: false
    default: us-west-1
  apigateway-name:
    description: API Gateway name
    required: true
  apigateway-stage-name:
    description: API gateway stage name
    required: false
    default: live

runs:
  using: 'composite'
  steps:
    - id: aws-creds
      uses: aws-actions/configure-aws-credentials@master
      with:
        role-to-assume: ${{ inputs.aws-role-arn }}
        aws-region: ${{ inputs.aws-region }}

    - id: deploy
      shell: bash
      run: aws apigateway create-deployment --rest-api-id $(aws apigateway get-rest-apis --query "items[?name=='${{ inputs.apigateway-name }}'].id" --output text) --stage-name ${{ inputs.apigateway-stage-name }}
