name: 'ww-build-python'
description: 'Package and publish a python lambda deployment object'

inputs:
  aws-role-arn:
    description: 'AWS IAM role to execute as'
    required: true
  aws-region:
    description: "AWS region"
    required: false
    default: us-west-1
  node-version:
    description: Python version
    required: false
    default: '3.9'
  artifact-bucket:
    description: S3 bucket for deployment artifact
    required: true
  working-directory:
    description: Working directory of python project
    required: false
    default: '.'
  zipfile:
    description: Filename of output archive
    required: false
    default: 'false'
  exclusions:
    description: List of excluded files or directories.
    required: false
    default: 'false'
  include:
    description: Paths or files to include
    required: true

runs:
  using: 'composite'
  steps:
    - id: aws-creds
      uses: aws-actions/configure-aws-credentials@master
      with:
        role-to-assume: ${{ inputs.aws-role-arn }}
        aws-region: ${{ inputs.aws-region }}

    - id: setup-python
      uses: actions/setup-python@v4.0.0
      with:
        python-version: ${{ inputs.python-version }}

    - id: dependencies
      continue-on-error: true
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: pip install -r requirements.txt

    - id: archive
      uses: thedoctor0/zip-release@main
      working-directory: ${{ inputs.working-directory }}
      with:
        type: zip
        filename: ${{ inputs.zipfile }}
        exclusions: ${{ inputs.exclusions == 'false' && '*.git* /*infrastructure/* Makefile' || inputs.exclusions }}
        path: ${{ inputs.include }}

    - id: publish
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
          aws s3 cp ${{ inputs.zipfile }} s3://${{ inputs.artifact-bucket }}/${{ inputs.zipfile }}
          aws s3api put-object-tagging \
            --bucket ${{ inputs.artifact-bucket }} \
            --key ${{ inputs.zipfile }} \
            --tagging "TagSet=[{Key=GIT_HASH,Value=$GITHUB_SHA}]"
